[0m[[0m[31merror[0m] [0m[0mjava.lang.RuntimeException: Failed to connect to zookeeper (zoo1,zoo2,zoo3) within 2x zookeeper timeout period 30000[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.fate.zookeeper.ZooSession.connect(ZooSession.java:162)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.fate.zookeeper.ZooSession.getSession(ZooSession.java:215)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.fate.zookeeper.ZooSession.getAnonymousSession(ZooSession.java:188)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.fate.zookeeper.ZooReader.getZooKeeper(ZooReader.java:62)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.fate.zookeeper.ZooCache.getZooKeeper(ZooCache.java:150)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.fate.zookeeper.ZooCache$2.run(ZooCache.java:384)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.fate.zookeeper.ZooCache$2.run(ZooCache.java:357)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.fate.zookeeper.ZooCache$ZooRunnable.retry(ZooCache.java:249)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.fate.zookeeper.ZooCache.get(ZooCache.java:412)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.fate.zookeeper.ZooCache.get(ZooCache.java:342)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.clientImpl.ClientContext.getInstanceID(ClientContext.java:565)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.client.ZooKeeperInstance.getInstanceID(ZooKeeperInstance.java:130)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.client.ZooKeeperInstance.<init>(ZooKeeperInstance.java:112)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.accumulo.core.client.ZooKeeperInstance.<init>(ZooKeeperInstance.java:124)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.locationtech.geomesa.accumulo.data.AccumuloDataStoreFactory$.buildAccumuloConnector(AccumuloDataStoreFactory.scala:185)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.locationtech.geomesa.accumulo.data.AccumuloDataStoreFactory.createDataStore(AccumuloDataStoreFactory.scala:43)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.locationtech.geomesa.accumulo.data.AccumuloDataStoreFactory.createDataStore(AccumuloDataStoreFactory.scala:36)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.geotools.data.DataAccessFinder.getDataStore(DataAccessFinder.java:119)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.geotools.data.DataStoreFinder.getDataStore(DataStoreFinder.java:69)[0m
[0m[[0m[31merror[0m] [0m[0m	at CountByDay$.delayedEndpoint$CountByDay$1(Main.scala:38)[0m
[0m[[0m[31merror[0m] [0m[0m	at CountByDay$delayedInit$body.apply(Main.scala:15)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.App$$anonfun$main$1.apply(App.scala:76)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.App$$anonfun$main$1.apply(App.scala:76)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.immutable.List.foreach(List.scala:392)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.App$class.main(App.scala:76)[0m
[0m[[0m[31merror[0m] [0m[0m	at CountByDay$.main(Main.scala:15)[0m
[0m[[0m[31merror[0m] [0m[0m	at CountByDay.main(Main.scala)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:566)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:144)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:94)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:187)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1986)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1925)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:367)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:834)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrun[0m) Failed to connect to zookeeper (zoo1,zoo2,zoo3) within 2x zookeeper timeout period 30000[0m
